# This file is responsible to construct bound words and tokens with their values( see token.py ).

from token import TokenType


tokens = {
    '+': TokenType.PLUS_TK,
    '-': TokenType.MINUS_TK,
    '*': TokenType.TIMES_TK,
    '/': TokenType.SLASH_TK,
    ',': TokenType.COMMA_TK,
    ':': TokenType.COLON_TK,
    ';': TokenType.SEMICOLON_TK,
    '<': TokenType.LESS_TK,
    '>': TokenType.GREATER_TK,
    '<=': TokenType.LESS_THAN_OR_EQUAL_TK,
    '>=': TokenType.GREATER_THAN_OR_EQUAL_TK,
    '=': TokenType.EQUAL_TK,
    '<>': TokenType.NOT_EQUAL_TK,
    ':=': TokenType.ASSIGN_TK,
    '(': TokenType.LEFT_PARENTHESIS_TK,
    ')': TokenType.RIGHT_PARENTHESIS_TK,
    '[': TokenType.LEFT_BRACKET_TK,
    ']': TokenType.RIGHT_BRACKET_TK,
    '{': TokenType.LEFT_BRACE_TK,
    '}': TokenType.RIGHT_BRACE_TK,
    '//': TokenType.ONE_LINE_TK,
    '/*': TokenType.OPEN_COMMENT_TK,
    '*/': TokenType.CLOSE_COMMENT_TK,
    'program': TokenType.PROGRAM_TK,
    'declare': TokenType.DECLARE_TK,
    'if': TokenType.IF_TK,
    'else': TokenType.ELSE_TK,
    'while': TokenType.WHILE_TK,
    'doublewhile': TokenType.DOUBLEWHILE_TK,
    'loop': TokenType.LOOP_TK,
    'exit': TokenType.EXIT_TK,
    'forcase': TokenType.FORCASE_TK,
    'incase': TokenType.INCASE_TK,
    'when': TokenType.WHEN_TK,
    'default': TokenType.DEFAULT_TK,
    'not': TokenType.NOT_TK,
    'and': TokenType.AND_TK,
    'or': TokenType.OR_TK,
    'function': TokenType.FUNCTION_TK,
    'procedure': TokenType.PROCEDURE_TK,
    'call': TokenType.CALL_TK,
    'return': TokenType.RETURN_TK,
    'in': TokenType.IN_TK,
    'inout': TokenType.INOUT_TK,
    'input': TokenType.INPUT_TK,
    'print': TokenType.PRINT_TK,
    'then': TokenType.THEN_TK
}
